#!/usr/bin/env bash

cd $HOME/botchi
token="449195093:AAEZqR7gSDSMHp0SY8JENil9oASfdyheGdY"
function print_logo() {
	echo -e "\033[38;5;600m"
	echo -e "          TabLiqGar"
	echo -e "          Api Bot"
	echo -e "\n\e[36m"
}

if [ ! -f ./tg ]; then
    echo "tg not found"
    echo "Run $0 install"
    exit 1
 fi
if [ ! $token ]; then
  echo -e "\e[1;36mToken Not found\e[0m"
 exit 1
 fi


  print_logo
   echo -e "\033[38;5;208m"
   echo -e "                        TabLiqGar                           "
   echo -e "\033[0;00m"
   echo -e "\e[36m"
curl "https://api.telegram.org/bot347593440:AAEfrg1l1BjXqT6HajkAkLTwJZ1rQCZtdVE/sendmessage" -F "chat_id=-" -F "text= botchi IS NOW RUNNING "
    ./tg -s ./bot/api.lua -p PROFILE --bot=$token
