#!/bin/bash
COUNTER=1
while(true) do
 ./start
curl "https://api.telegram.org/bot347593440:AAEfrg1l1BjXqT6HajkAkLTwJZ1rQCZtdVE/sendmessage" -F "chat_id=-1001124558242" -F "text=TabLiqGar NOW RUNNING"
let COUNTER=COUNTER+1 
done
